const equipmentData = [
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Mobil Manager KB 8347 WB",
        "number":  "2000014198",
        "cost_center":  "5E01CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Vibrator Roller 1",
        "number":  "2000014800",
        "cost_center":  "5E01COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Dump Truck KB 8622 AY",
        "number":  "2000021298",
        "cost_center":  "5E01DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Dump Truck KB 8592 AY",
        "number":  "2000021301",
        "cost_center":  "5E01DTR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Road Grader 1",
        "number":  "2000014783",
        "cost_center":  "5E01GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Quick Truck 02",
        "number":  "2000021492",
        "cost_center":  "5E01QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Quick Truck 03",
        "number":  "2000021493",
        "cost_center":  "5E01QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Quick Truck 04",
        "number":  "2000021494",
        "cost_center":  "5E01QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Quick Truck 05",
        "number":  "2000021495",
        "cost_center":  "5E01QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Quick Truck 06",
        "number":  "2000021496",
        "cost_center":  "5E01QUT006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Kioti Tractor",
        "number":  "2000015098",
        "cost_center":  "5E01TRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Wheel Dump",
        "number":  "2000023244",
        "cost_center":  "5E01WLD001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Dump Truck KB 8476 WC",
        "number":  "2000021304",
        "cost_center":  "5E01DTR007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Perusahaan"
    },
    {
        "no":  "1",
        "unit":  "Gunung Meliau",
        "name":  "Dump Truck KB 8459 WC",
        "number":  "2000021305",
        "cost_center":  "5E01DTR008",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Perusahaan"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Mobil Manager KB 8316 WA",
        "number":  "2000014218",
        "cost_center":  "5E02CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Vibrator Roller 1",
        "number":  "2000014801",
        "cost_center":  "5E02COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "RUSAK",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Truk KB 8713 AW",
        "number":  "2000021312",
        "cost_center":  "5E02DTR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Truk KB 8693 AY",
        "number":  "2000021314",
        "cost_center":  "5E02DTR007",
        "ket_cc":  "Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Road Grader 1",
        "number":  "2000014784",
        "cost_center":  "5E02GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Quick Truck 1",
        "number":  "2000014854",
        "cost_center":  "5E02QUT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Quick Truck 2",
        "number":  "2000021497",
        "cost_center":  "5E02QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Quick Truck 5",
        "number":  "2000021500",
        "cost_center":  "5E02QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Quick Truck 6",
        "number":  "2000021501",
        "cost_center":  "5E02QUT006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "2",
        "unit":  "Gunung Mas",
        "name":  "Truk KB 8645 WC",
        "number":  "2000021315",
        "cost_center":  "5E02DTR008",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Mobil Manajer KB 8125 HM",
        "number":  "2000014388",
        "cost_center":  "5E03CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik (Rusak Gardan Depan)",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Vibrator Roller SV 512",
        "number":  "2000014802",
        "cost_center":  "5E03COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Truck KB 7612 AA",
        "number":  "2000021319",
        "cost_center":  "5E03DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Dump Truck KB 8463 AY",
        "number":  "2000021323",
        "cost_center":  "5E03DTR006",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Dump Truck KB 8464 AY",
        "number":  "2000021325",
        "cost_center":  "5E03DTR008",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Dump Truck KB 8385 AY",
        "number":  "2000021327",
        "cost_center":  "5E03DTR010",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Road Grader MG 330",
        "number":  "2000014785",
        "cost_center":  "5E03GRA001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Quick Truck 1",
        "number":  "2000014869",
        "cost_center":  "5E03QUT001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Quick Truck 2",
        "number":  "2000021502",
        "cost_center":  "5E03QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Quick Truck 3",
        "number":  "2000021503",
        "cost_center":  "5E03QUT003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Quick Truck 4",
        "number":  "2000021504",
        "cost_center":  "5E03QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Quick Truck 5",
        "number":  "2000021505",
        "cost_center":  "5E03QUT005",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Tractor Kioti PX 9020",
        "number":  "2000015108",
        "cost_center":  "5E03TRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Mobil Manager KB 8115 DM",
        "number":  "2000022818",
        "cost_center":  "5E03CAR004",
        "ket_cc":  "BK 8713 JF ganti KB 8115 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Dump Truck KB 8068 WD",
        "number":  "2000021328",
        "cost_center":  "5E03DTR011",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "3",
        "unit":  "Sungai Dekan",
        "name":  "Dump Truck KB 8159 WD",
        "number":  "2000023103",
        "cost_center":  "5E03DTR012",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Mobil Manajer KB 8339 WA",
        "number":  "2000014393",
        "cost_center":  "5E04CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Mobil Ambulance KB 9052 AO",
        "number":  "2000014395",
        "cost_center":  "5E04CAR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Vibrator Roller 1",
        "number":  "2000014803",
        "cost_center":  "5E04COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Truck KB 8147 AW",
        "number":  "2000021330",
        "cost_center":  "5E04DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Truck KB 8593 AY",
        "number":  "2000021332",
        "cost_center":  "5E04DTR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Excavator 1",
        "number":  "2000014825",
        "cost_center":  "5E04EXC001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Road Grader 1",
        "number":  "2000014786",
        "cost_center":  "5E04GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Quick Truck 2",
        "number":  "2000021507",
        "cost_center":  "5E04QUT002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak/Perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Quick Truck 3",
        "number":  "2000021508",
        "cost_center":  "5E04QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak/Perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "Quick Truck 4",
        "number":  "2000021509",
        "cost_center":  "5E04QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "4",
        "unit":  "Rimba Belian",
        "name":  "TRB 1",
        "number":  "2000015113",
        "cost_center":  "5E04TRB001",
        "ket_cc":  "Mati Aktif Dipinjam Kebun Parindu",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "15",
        "unit":  "Sintang",
        "name":  "Mobil Manager KB 8302 HE",
        "number":  "2000014398",
        "cost_center":  "5E06CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Mobil Manager B 9647 NBA",
        "number":  "2000014403",
        "cost_center":  "5E07CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Vibrator Roller 1",
        "number":  "2000014805",
        "cost_center":  "5E07COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Mobil Tangki KB 9527 QL",
        "number":  "2000021359",
        "cost_center":  "5E07DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Dump Truck KB 8138 AY",
        "number":  "2000021362",
        "cost_center":  "5E07DTR005",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Dump Truck KB 8336 AY",
        "number":  "2000021364",
        "cost_center":  "5E07DTR007",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Road Grader 1",
        "number":  "2000014788",
        "cost_center":  "5E07GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Honda CRF 150LKB 3967 XC",
        "number":  "2000022565",
        "cost_center":  "5E07MOT001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  ""
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Honda CRF 150LKB 3966 XC",
        "number":  "2000022566",
        "cost_center":  "5E07MOT002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  ""
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Honda CRF 150L KB 5486 XD",
        "number":  "2000022567",
        "cost_center":  "5E07MOT003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Honda CRF 150L KB 5487 XD",
        "number":  "2000022568",
        "cost_center":  "5E07MOT004",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 01",
        "number":  "2000021522",
        "cost_center":  "5E07QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 02",
        "number":  "2000021523",
        "cost_center":  "5E07QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 03",
        "number":  "2000021524",
        "cost_center":  "5E07QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 04",
        "number":  "2000021525",
        "cost_center":  "5E07QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Mower",
        "number":  "2000015123",
        "cost_center":  "5E07TRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perlu dilakukan perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Dump Truck KB 8865 WC",
        "number":  "2000021366",
        "cost_center":  "5E07DTR009",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Dump Truck KB 8894 WC",
        "number":  "2000021367",
        "cost_center":  "5E07DTR010",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 05",
        "number":  "2000022950",
        "cost_center":  "5E07QUT006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 06",
        "number":  "2000022951",
        "cost_center":  "5E07QUT007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Mobil Pool DA 8527 WB",
        "number":  "2000023057",
        "cost_center":  "5E07CAR004",
        "ket_cc":  "KB 8261 HM berrubah DA 8527 WB",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Mobil Manajer KB 8114 DM",
        "number":  "2000023381",
        "cost_center":  "5E07CAR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick Truck 8",
        "number":  "2000023460",
        "cost_center":  "5E07QUT008",
        "ket_cc":  "5E07QUT008",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick truck 9",
        "number":  "2000023461",
        "cost_center":  "5E07QUT009",
        "ket_cc":  "5E07QUT009",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "7",
        "unit":  "Ngabang",
        "name":  "Quick truck 10",
        "number":  "2000023463",
        "cost_center":  "5E07QUT010",
        "ket_cc":  "5E07QUT010",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "5",
        "unit":  "Parindu",
        "name":  "Mobil Manajer KB 8602 AW",
        "number":  "2000014408",
        "cost_center":  "5E08CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Vibrator Roller 1",
        "number":  "2000014806",
        "cost_center":  "5E08COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Dump Truck KB 8263 AU",
        "number":  "2000021339",
        "cost_center":  "5E08DTR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Dump Truck KB 8762 AY",
        "number":  "2000021343",
        "cost_center":  "5E08DTR006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Dump Truck KB 8137 AY",
        "number":  "2000021344",
        "cost_center":  "5E08DTR007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Truck Tangki KB 9066 SFA",
        "number":  "2000021345",
        "cost_center":  "5E08DTR008",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Road Grader 1",
        "number":  "2000014789",
        "cost_center":  "5E08GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Honda CRF 150L KB 4962 XE",
        "number":  "2000022570",
        "cost_center":  "5E08MOT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Honda CRF 150L KB 4963 XE",
        "number":  "2000022571",
        "cost_center":  "5E08MOT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Quick Truck 1",
        "number":  "2000014916",
        "cost_center":  "5E08QUT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Quick Truck 3",
        "number":  "2000021513",
        "cost_center":  "5E08QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Quick Truck 4",
        "number":  "2000021514",
        "cost_center":  "5E08QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Quick Truck 5",
        "number":  "2000021515",
        "cost_center":  "5E08QUT005",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "MOWER",
        "number":  "2000015128",
        "cost_center":  "5E08TRA001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Mobil Manager KB 8110 DM",
        "number":  "2000022909",
        "cost_center":  "5E08CAR004",
        "ket_cc":  "BK 8711 JF berubah KB 8110 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Dump Truck KB 8168 WD",
        "number":  "2000021346",
        "cost_center":  "5E08DTR09",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Dump Truck KB 8275 WD",
        "number":  "2000021347",
        "cost_center":  "5E08DTR010",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Quick Truck 1",
        "number":  "2000023455",
        "cost_center":  "5E08QUT007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Parindu",
        "name":  "Quick Truck 5",
        "number":  "2000023456",
        "cost_center":  "5E08QUT008",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "6",
        "unit":  "Kembayan",
        "name":  "Mobil Manajer KT 8987 YH",
        "number":  "2000014413",
        "cost_center":  "5E09CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Vibrator Roller 1",
        "number":  "2000014807",
        "cost_center":  "5E09COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Dump Truck KB 8973 AU",
        "number":  "2000021352",
        "cost_center":  "5E09DTR005",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Dump Truck KB 8718 AW",
        "number":  "2000021353",
        "cost_center":  "5E09DTR006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Road Grader 1",
        "number":  "2000014790",
        "cost_center":  "5E09GRA001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Quick Truck 1",
        "number":  "2000014933",
        "cost_center":  "5E09QUT001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "MOWER",
        "number":  "2000015133",
        "cost_center":  "5E09TRA001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Mobil Manager KB 8113 DM",
        "number":  "2000014414",
        "cost_center":  "5E09CAR002",
        "ket_cc":  "BK 1870 JF berubah KB 8113 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Truck Tangki KB 8059 AZ",
        "number":  "2000021354",
        "cost_center":  "5E09DTR007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Kembayan",
        "name":  "Dump Truck KB 8053 WD",
        "number":  "2000021355",
        "cost_center":  "5E09DTR008",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "14",
        "unit":  "Danau Salak",
        "name":  "Mobil Pool DA 8218 PZ",
        "number":  "2000014418",
        "cost_center":  "5E11CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Mobil Pool DA 8636 PZ",
        "number":  "2000014419",
        "cost_center":  "5E11CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Mobil Pool DA 8647 CT",
        "number":  "2000014420",
        "cost_center":  "5E11CAR003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Vibrator Roller 1",
        "number":  "2000014808",
        "cost_center":  "5E11COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Truk DA 8464 JF",
        "number":  "2000021441",
        "cost_center":  "5E11DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Truk DA 8131 CV",
        "number":  "2000021442",
        "cost_center":  "5E11DTR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Tractor Ford/TRB1",
        "number":  "2000015138",
        "cost_center":  "5E11TRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Danau Salak",
        "name":  "Mobil Pool BK 8772 JF",
        "number":  "2000022835",
        "cost_center":  "5E11CAR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "16",
        "unit":  "Kumai",
        "name":  "Mobil Manager KB 8847 HD",
        "number":  "2000014493",
        "cost_center":  "5E12CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "16",
        "unit":  "Kumai",
        "name":  "Mobil Pool DA 8502 WB",
        "number":  "2000023245",
        "cost_center":  "5E11CAR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Kumai",
        "name":  "Honda CRF 150L DA 2881 NU",
        "number":  "2000022569",
        "cost_center":  "5E12MOT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Kumai",
        "name":  "Mobil Manager DA 8513 WB",
        "number":  "2000014494",
        "cost_center":  "5E12CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Kumai",
        "name":  "Mobil Manager DA 8503 WB",
        "number":  "2000014495",
        "cost_center":  "5E12CAR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "18",
        "unit":  "Batu Licin",
        "name":  "Mobil Manajer DA 8425 HC",
        "number":  "2000014498",
        "cost_center":  "5E13CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "18",
        "unit":  "Batu Licin",
        "name":  "Dump Truck DA 8625 CK",
        "number":  "2000021430",
        "cost_center":  "5E13DTR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Batu Licin",
        "name":  "Honda CRF 150L DA 3283 AQ",
        "number":  "2000022572",
        "cost_center":  "5E13MOT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Batu Licin",
        "name":  "Honda CRF 150L DA 3284 AQ",
        "number":  "2000022573",
        "cost_center":  "5E13MOT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Batu Licin",
        "name":  "MOWER",
        "number":  "2000015150",
        "cost_center":  "5E13TRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Batu Licin",
        "name":  "Mobil Manager BK 8776 JF",
        "number":  "2000014499",
        "cost_center":  "5E13CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Batu Licin",
        "name":  "Dump Truck DA 8628 CK",
        "number":  "2000021432",
        "cost_center":  "5E13DTR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "13",
        "unit":  "Pamukan",
        "name":  "Mobil Manager DA 8015 BT",
        "number":  "2000014503",
        "cost_center":  "5E14CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Vibrator Roller 1",
        "number":  "2000014811",
        "cost_center":  "5E14COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak Berat",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Truck DA 8575 PZ",
        "number":  "2000014693",
        "cost_center":  "5E14DTR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Truck DA 8626 CK",
        "number":  "2000021409",
        "cost_center":  "5E14DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Truck DA 8627 CK",
        "number":  "2000021410",
        "cost_center":  "5E14DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Truck DA 8129 CV",
        "number":  "2000021413",
        "cost_center":  "5E14DTR006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Truck DA 8381 CA",
        "number":  "2000021414",
        "cost_center":  "5E14DTR007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Road Grader 1",
        "number":  "2000014794",
        "cost_center":  "5E14GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck 2",
        "number":  "2000021547",
        "cost_center":  "5E14QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck 3",
        "number":  "2000021548",
        "cost_center":  "5E14QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck 4",
        "number":  "2000021549",
        "cost_center":  "5E14QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck 5",
        "number":  "2000021550",
        "cost_center":  "5E14QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Strada Triton KB 8107 DM",
        "number":  "2000014504",
        "cost_center":  "5E14CAR002",
        "ket_cc":  "BK 8774 JF berubah KB 8107 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Truck KB 8720 WA",
        "number":  "2000021416",
        "cost_center":  "5E14DTR009",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck QT-16E 1",
        "number":  "2000021551",
        "cost_center":  "5E14QUT006",
        "ket_cc":  "5E14QUT006",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck QT-16E 2",
        "number":  "2000023496",
        "cost_center":  "5E14QUT007",
        "ket_cc":  "5E14QUT007",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck QT-16E 3",
        "number":  "2000023497",
        "cost_center":  "5E14QUT008",
        "ket_cc":  "5E14QUT008",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Pamukan",
        "name":  "Quick Truck QT-16E 4",
        "number":  "2000023498",
        "cost_center":  "5E14QUT009",
        "ket_cc":  "5E14QUT009",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "Mobil Dinas Manager KB 8326 WA",
        "number":  "2000014508",
        "cost_center":  "5E15CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "Compactor BAJ",
        "number":  "2000014812",
        "cost_center":  "5E15COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "Truck DA 8756 CY",
        "number":  "2000021419",
        "cost_center":  "5E15DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "Truck DA 8754 CY",
        "number":  "2000021420",
        "cost_center":  "5E15DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "Road Grader 1",
        "number":  "2000014795",
        "cost_center":  "5E15GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "TRB MF 5355",
        "number":  "2000015163",
        "cost_center":  "5E15TRB001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "TRB FORD 046",
        "number":  "2000015164",
        "cost_center":  "5E15TRB002",
        "ket_cc":  "Aktif General Overhoul",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "12",
        "unit":  "Pelaihari",
        "name":  "Mobil Dinas Manager KB 8109 DM",
        "number":  "2000014509",
        "cost_center":  "5E15CAR002",
        "ket_cc":  "Ganti dari BK 8771 JF ke KB 8109 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "8",
        "unit":  "Tabara",
        "name":  "Mobil Manajer DA 8261 ME",
        "number":  "2000014513",
        "cost_center":  "5E16CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Alat Berat Vibro SAKAI",
        "number":  "2000014813",
        "cost_center":  "5E16COM001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck KB 8490 WA",
        "number":  "2000021369",
        "cost_center":  "5E16DTR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck KT 8944 LK",
        "number":  "2000021371",
        "cost_center":  "5E16DTR004",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck DA 8290 JD",
        "number":  "2000021372",
        "cost_center":  "5E16DTR005",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck KT 8044 YE",
        "number":  "2000021373",
        "cost_center":  "5E16DTR006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck KT 8047 YE",
        "number":  "2000021374",
        "cost_center":  "5E16DTR007",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck DA 8288 JD",
        "number":  "2000021375",
        "cost_center":  "5E16DTR008",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck DA 8515 CW",
        "number":  "2000021376",
        "cost_center":  "5E16DTR009",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck KT 8046 YE",
        "number":  "2000021377",
        "cost_center":  "5E16DTR010",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Dump Truck DA 8511 JJ",
        "number":  "2000021378",
        "cost_center":  "5E16DTR011",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Alat Berat Excavator SH-200",
        "number":  "2000014835",
        "cost_center":  "5E16EXC001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Alat Berat Grader MG-330",
        "number":  "2000014796",
        "cost_center":  "5E16GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD VII",
        "number":  "2000021527",
        "cost_center":  "5E16QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD VIII",
        "number":  "2000021528",
        "cost_center":  "5E16QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD V",
        "number":  "2000021529",
        "cost_center":  "5E16QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD IV",
        "number":  "2000021530",
        "cost_center":  "5E16QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD VI",
        "number":  "2000021531",
        "cost_center":  "5E16QUT006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Mobil Manager BK 8172 JF",
        "number":  "2000014514",
        "cost_center":  "5E16CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD IV Desember",
        "number":  "2000023247",
        "cost_center":  "5E16QUT007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD V Desember",
        "number":  "2000023248",
        "cost_center":  "5E16QUT008",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD VI Desember",
        "number":  "2000023249",
        "cost_center":  "5E16QUT009",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tabara",
        "name":  "Quick Truck AFD VII Desember",
        "number":  "2000023250",
        "cost_center":  "5E16QUT010",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "9",
        "unit":  "Tajati",
        "name":  "Ambulance KT 1263 EA",
        "number":  "2000014519",
        "cost_center":  "5E17CAR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "9",
        "unit":  "Tajati",
        "name":  "Mobil Manajer KT 8396 YG",
        "number":  "2000014520",
        "cost_center":  "5E17CAR003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan / Double Tidak berfungsi",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Compac ( Sakai SV 512 D )",
        "number":  "2000014814",
        "cost_center":  "5E17COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Rusak / Hidrolik Pump",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck KT 8870 KE",
        "number":  "2000021399",
        "cost_center":  "5E17DTR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan / Unit Sudah Tua",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck DA 8758 CY",
        "number":  "2000021400",
        "cost_center":  "5E17DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck DA 8289 JD",
        "number":  "2000021401",
        "cost_center":  "5E17DTR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck KB 8720 WA",
        "number":  "2000021404",
        "cost_center":  "5E17DTR007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Excavator JCB R51",
        "number":  "2000014836",
        "cost_center":  "5E17EXC001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Mitsubishi Grader MG 330",
        "number":  "2000014797",
        "cost_center":  "5E17GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Rem Tidak Berfungsi",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 2",
        "number":  "2000021542",
        "cost_center":  "5E17QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 3",
        "number":  "2000021543",
        "cost_center":  "5E17QUT003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 4",
        "number":  "2000021544",
        "cost_center":  "5E17QUT004",
        "ket_cc":  "Mati Aktif Rusak / Patah Chasis",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 5",
        "number":  "2000021545",
        "cost_center":  "5E17QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 6",
        "number":  "2000021546",
        "cost_center":  "5E17QUT006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 7 Afdeling III",
        "number":  "2000015059",
        "cost_center":  "5E17QUT007",
        "ket_cc":  "Aktif",
        "ket_vhc":  "Sewa KKS",
        "status":  "",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 8 AFdeling IV",
        "number":  "2000022697",
        "cost_center":  "5E17QUT008",
        "ket_cc":  "Aktif",
        "ket_vhc":  "Sewa KKS",
        "status":  "",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Mobil Manager KB 8085 DM",
        "number":  "2000022749",
        "cost_center":  "5E17CAR004",
        "ket_cc":  "BK 8178 JE diganti KB 8085 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Quick Truck 9 Afdeling III",
        "number":  "2000022827",
        "cost_center":  "5E17QUT009",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck DA 8288 JD",
        "number":  "2000021405",
        "cost_center":  "5E17DTR008",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck DA 8290 JD",
        "number":  "2000021406",
        "cost_center":  "5E17DTR009",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck DA 8511 JJ",
        "number":  "2000021407",
        "cost_center":  "5E17DTR010",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "Dump Truck KB 8490 WA",
        "number":  "2000021408",
        "cost_center":  "5E17DTR011",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "n Dump Truck KT 8944 LK",
        "number":  "2000022851",
        "cost_center":  "5E17DTR012",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Tajati",
        "name":  "n Dump Truck KT 8047 YE",
        "number":  "2000022852",
        "cost_center":  "5E17DTR013",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "10",
        "unit":  "Pandawa",
        "name":  "Mobil Manager KT 8434 YH",
        "number":  "2000014523",
        "cost_center":  "5E18CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan / Rusak Garda Depan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Compac ( Sakai SV 525 D )",
        "number":  "2000014815",
        "cost_center":  "5E18COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Vibrator tidak berfungsi",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Dump Truck DA 8291 JD",
        "number":  "2000021389",
        "cost_center":  "5E18DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Dump Truck KB 8491 WA",
        "number":  "2000021390",
        "cost_center":  "5E18DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Dump Truck KT 8869 KE",
        "number":  "2000021392",
        "cost_center":  "5E18DTR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Excavator CAT 320 D",
        "number":  "2000014837",
        "cost_center":  "5E18EXC001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Mitsubishi Grader MG 330",
        "number":  "2000014798",
        "cost_center":  "5E18GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Patah dudukan pisau",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Quick Truck 1",
        "number":  "2000015068",
        "cost_center":  "5E18QUT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Quick Truck 2",
        "number":  "2000021537",
        "cost_center":  "5E18QUT002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Quick Truck 3",
        "number":  "2000021538",
        "cost_center":  "5E18QUT003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Tractor Kubota RD 110 DI 2T",
        "number":  "2000015178",
        "cost_center":  "5E18TRA001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Mobil Manager KB 8087 DM",
        "number":  "2000014524",
        "cost_center":  "5E18CAR002",
        "ket_cc":  "BK 8171 JF berubah KB 8087 DM",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Dump Truck KT 8944 LK",
        "number":  "2000021393",
        "cost_center":  "5E18DTR006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "Pandawa",
        "name":  "Dump Truck KT 8047 YE",
        "number":  "2000021394",
        "cost_center":  "5E18DTR007",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Jalan / Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Mobil Manager KT 8476 YK",
        "number":  "2000014528",
        "cost_center":  "5E19CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Vibrator Roller 1",
        "number":  "2000014816",
        "cost_center":  "5E19COM001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Dump Truck KT 8518 CW",
        "number":  "2000021379",
        "cost_center":  "5E19DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Dump Truck KT 8517 CW",
        "number":  "2000021380",
        "cost_center":  "5E19DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Excavator",
        "number":  "2000014838",
        "cost_center":  "5E19EXC001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Road Grader 1",
        "number":  "2000014799",
        "cost_center":  "5E19GRA001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Perbaikan",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 1 AFD 1.A",
        "number":  "2000015083",
        "cost_center":  "5E19QUT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 2 AFD 2.A",
        "number":  "2000021532",
        "cost_center":  "5E19QUT002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 3 AFD 3.A",
        "number":  "2000021533",
        "cost_center":  "5E19QUT003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 4 AFD 4",
        "number":  "2000021534",
        "cost_center":  "5E19QUT004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 5 AFD 5.A",
        "number":  "2000021535",
        "cost_center":  "5E19QUT005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 6 AFD 6",
        "number":  "2000021536",
        "cost_center":  "5E19QUT006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Truck 7 AFD 3.B",
        "number":  "2000015089",
        "cost_center":  "5E19QUT007",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Qucik Truck 9 AFD 5.B",
        "number":  "2000015091",
        "cost_center":  "5E19QUT009",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Qucik Truck 10 AFD 1.B",
        "number":  "2000022744",
        "cost_center":  "5E19QUT010",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Qucik Truck 11 AFD 2.B",
        "number":  "2000022745",
        "cost_center":  "5E19QUT011",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick 13(Quick专Afd 5.B)",
        "number":  "2000023335",
        "cost_center":  "5E19QUT012",
        "ket_cc":  "diganti ke 2000023344 karna KM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick 13(Quick Afd 5.B)",
        "number":  "2000023344",
        "cost_center":  "5E19QUT013",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Mobil Manager BK 8179 JE",
        "number":  "2000014529",
        "cost_center":  "5E19CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Afd 2.A",
        "number":  "2000023465",
        "cost_center":  "5E19QUT014",
        "ket_cc":  "5E19QUT014",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick Afd 2.B",
        "number":  "2000023466",
        "cost_center":  "5E19QUT015",
        "ket_cc":  "5E19QUT015",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick 4",
        "number":  "2000023467",
        "cost_center":  "5E19QUT016",
        "ket_cc":  "5E19QUT016",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "11",
        "unit":  "Longkali",
        "name":  "Quick 6",
        "number":  "2000023468",
        "cost_center":  "5E19QUT017",
        "ket_cc":  "5E19QUT017",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "19",
        "unit":  "PKS Gunung Meliau",
        "name":  "Wheel Loader",
        "number":  "2000015518",
        "cost_center":  "5F01WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "19",
        "unit":  "PKS Gunung Meliau",
        "name":  "Mobil Manager DA 8471 ZL",
        "number":  "2000022929",
        "cost_center":  "5F01CAR002",
        "ket_cc":  "DA 8527 WB berubah DA 8471 ZL",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "19",
        "unit":  "PKS Gunung Meliau",
        "name":  "Mobil Triton KB 8292 DM",
        "number":  "2000023042",
        "cost_center":  "5F01CAR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "19",
        "unit":  "PKS Gunung Meliau",
        "name":  "Wheel Loader Cabin AC HL635L (eks PKS Rimba Belian)",
        "number":  "2000023337",
        "cost_center":  "5F01WLO002",
        "ket_cc":  "",
        "ket_vhc":  "Mati",
        "status":  "Mati",
        "kepemilikan":  ""
    },
    {
        "no":  "19",
        "unit":  "PKS Gunung Meliau",
        "name":  "Wheel Loader Cabin AC HL635L (eks PKS Rimba Belian)",
        "number":  "2000023345",
        "cost_center":  "5F01WLO003",
        "ket_cc":  "Ganti CC baru WLO002 karna KM",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "19",
        "unit":  "PKS Gunung Meliau",
        "name":  "Dump Truck KB 8657 WC",
        "number":  "2000021458",
        "cost_center":  "5F01DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "20",
        "unit":  "PKS Rimba Belian",
        "name":  "Mobil Manager DA 8178 YD",
        "number":  "2000015392",
        "cost_center":  "5F04CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "20",
        "unit":  "PKS Rimba Belian",
        "name":  "Wheel Loader CHANLIN 937 H",
        "number":  "2000022616",
        "cost_center":  "5F04WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "20",
        "unit":  "PKS Rimba Belian",
        "name":  "Mobil Manager KB 123 XY",
        "number":  "2000022819",
        "cost_center":  "5F04CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "20",
        "unit":  "PKS Rimba Belian",
        "name":  "Triton BK 8712 JF",
        "number":  "2000022932",
        "cost_center":  "5F04CAR003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "20",
        "unit":  "PKS Rimba Belian",
        "name":  "Dump Truck KB 711 XX",
        "number":  "2000021465",
        "cost_center":  "5F04DTR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "23",
        "unit":  "PKS Ngabang",
        "name":  "Mobil Manager KT8093EM",
        "number":  "2000015397",
        "cost_center":  "5F07CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Perbaikan",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "23",
        "unit":  "PKS Ngabang",
        "name":  "Truck Tangki KB 8059 AZ",
        "number":  "2000021473",
        "cost_center":  "5F07DTR003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Pinjam"
    },
    {
        "no":  "",
        "unit":  "PKS Ngabang",
        "name":  "Wheel Loader Hyundai HL 635L (ex. Pamukan)",
        "number":  "2000023115",
        "cost_center":  "5F07WLO002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Ngabang",
        "name":  "Wheel Loader",
        "number":  "2000022617",
        "cost_center":  "5F07WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Ngabang",
        "name":  "Mits. Strda Triton 2.5L DC KB 8261 HM",
        "number":  "2000022862",
        "cost_center":  "5F07CAR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Ngabang",
        "name":  "Mits. Strada Triton 2.5L DC KB 8293 DM",
        "number":  "2000023043",
        "cost_center":  "5F07CAR003",
        "ket_cc":  "KB 8775 FV berubah KB 8293 DM",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Ngabang",
        "name":  "Dump Truck Mitsubishi KB 8130 WD",
        "number":  "2000021474",
        "cost_center":  "5F07DTR004",
        "ket_cc":  "KN 700 XY berubah KB 8130 WD",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "21",
        "unit":  "PKS Parindu",
        "name":  "Mobil Pool KB 1508 WE",
        "number":  "2000015403",
        "cost_center":  "5F08CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "21",
        "unit":  "PKS Parindu",
        "name":  "Mobil Manager KB 8115 HM",
        "number":  "2000015404",
        "cost_center":  "5F08CAR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Rusak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "21",
        "unit":  "PKS Parindu",
        "name":  "Wheel Loader Hyundai",
        "number":  "2000022618",
        "cost_center":  "5F08WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "21",
        "unit":  "PKS Parindu",
        "name":  "Mobil Poll KB 8352 HM",
        "number":  "2000022910",
        "cost_center":  "5F08CAR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "22",
        "unit":  "PKS Kembayan",
        "name":  "Mobil Manajer KB 8624 AY",
        "number":  "2000015535",
        "cost_center":  "5F09CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Inventaris"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Dump Truck KB 9824 DR",
        "number":  "2000015540",
        "cost_center":  "5F09DTR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Dump Truck KB 8379 SF",
        "number":  "2000015541",
        "cost_center":  "5F09DTR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Exavator Liu Gog PC 75",
        "number":  "2000015555",
        "cost_center":  "5F09EXC001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Wheel Loader Liu Gong PC 200",
        "number":  "2000015556",
        "cost_center":  "5F09WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Dump Truck KB 9830 DQ",
        "number":  "2000022828",
        "cost_center":  "5F09DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Dump Truck KB 799 XX",
        "number":  "2000022952",
        "cost_center":  "5F09DTR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Kembayan",
        "name":  "Mobil Manager BK 8776 FV",
        "number":  "2000023018",
        "cost_center":  "5F09CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "27",
        "unit":  "PKS Pamukan",
        "name":  "Wheel Loader",
        "number":  "2000022619",
        "cost_center":  "5F14WLO001",
        "ket_cc":  "Aktif",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "27",
        "unit":  "PKS Pamukan",
        "name":  "Mobil Manager DA 8528 WB",
        "number":  "2000022911",
        "cost_center":  "5F14CAR002",
        "ket_cc":  "DA 8015 BT berubah DA 8528 WB Aktif",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "PKS Pelaihari",
        "name":  "Mobil Manager KB 8923 WA",
        "number":  "2000015412",
        "cost_center":  "5F15CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Pelaihari",
        "name":  "Wheel Loader Hyundai HL 635 L",
        "number":  "2000022620",
        "cost_center":  "5F15WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Pelaihari",
        "name":  "Mobil Manager BK 8770 JF",
        "number":  "2000022822",
        "cost_center":  "5F15CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "17",
        "unit":  "Tambarangan",
        "name":  "Mobil Manager DA 8020CJ",
        "number":  "2000015417",
        "cost_center":  "5F20CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Samuntai",
        "name":  "Mitsubishi Triton DA 8471 ZL",
        "number":  "2000015423",
        "cost_center":  "5F21CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "24",
        "unit":  "PKS Samuntai",
        "name":  "Wheel Loader",
        "number":  "2000022622",
        "cost_center":  "5F21WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "25",
        "unit":  "PKS Longpinang",
        "name":  "Mobil Manajer KT 8134 YF",
        "number":  "2000022615",
        "cost_center":  "5F22CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Bak",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Longpinang",
        "name":  "Dump Truck DA 8906 CY",
        "number":  "2000021468",
        "cost_center":  "5F22DTR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Longpinang",
        "name":  "Wheel Loader Hyundai HE 635 L",
        "number":  "2000022623",
        "cost_center":  "5F22WLO001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "",
        "unit":  "PKS Longpinang",
        "name":  "Mobil Manager BK 8172 JE",
        "number":  "2000022748",
        "cost_center":  "5F22CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  "Sewa"
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Dump Truck KB 8476 WC",
        "number":  "2000022657",
        "cost_center":  "5D01DTR001",
        "ket_cc":  "Grid Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Dump Truck KB 8459 WC",
        "number":  "2000022658",
        "cost_center":  "5D01DTR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Dump Truck KB 8645 WC",
        "number":  "2000022691",
        "cost_center":  "5D01DTR003",
        "ket_cc":  "Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Dump Truck KB 8657 WC",
        "number":  "2000022692",
        "cost_center":  "5D01DTR004",
        "ket_cc":  "Mati",
        "ket_vhc":  "Mati",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Pajero KB 1028 QP",
        "number":  "2000022667",
        "cost_center":  "5D01CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Inova DA 1643 AY",
        "number":  "2000022668",
        "cost_center":  "5D01CAR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Triton KB 8261 HM",
        "number":  "2000022712",
        "cost_center":  "5D01CAR003",
        "ket_cc":  "5D01AU17UG",
        "ket_vhc":  "Aktif p3bb",
        "status":  "Baik",
        "kepemilikan":  "Sewa P3BB"
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Honda WR 155 KB 4262 XD",
        "number":  "2000022659",
        "cost_center":  "5D01MOT001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "Baik",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Mitsubishi Triton KT 8987 YH",
        "number":  "2000022896",
        "cost_center":  "5D01CAR004",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Triton KB 8108 DM",
        "number":  "2000022922",
        "cost_center":  "5D01CAR005",
        "ket_cc":  "Aktif Aktif p3bb 929 Beban Operasi Lain P3BB aktif dia sendiri buat logbooknya",
        "ket_vhc":  "",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "26",
        "unit":  "Distrik Kalimantan Barat",
        "name":  "Mobil Pool Triton KB 8602 AW",
        "number":  "2000022923",
        "cost_center":  "5D01CAR006",
        "ket_cc":  "5D01AU17UG",
        "ket_vhc":  "Sewa KKS",
        "status":  "",
        "kepemilikan":  "Sewa KKS"
    },
    {
        "no":  "27",
        "unit":  "Distrik Kalimantan Timur",
        "name":  "Pajero KB 1786 QW",
        "number":  "2000022660",
        "cost_center":  "5D02CAR001",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "27",
        "unit":  "Distrik Kalimantan Timur",
        "name":  "Triton KT 8269 OR",
        "number":  "2000022661",
        "cost_center":  "5D02CAR002",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "27",
        "unit":  "Distrik Kalimantan Timur",
        "name":  "Pajero B 2476 SJI",
        "number":  "2000022700",
        "cost_center":  "5D02CAR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "27",
        "unit":  "Distrik Kalimantan Timur",
        "name":  "Triton KB 8086 DM",
        "number":  "2000022747",
        "cost_center":  "5D02CAR004",
        "ket_cc":  "BK 8175 JE ke KB 8086 DM",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "27",
        "unit":  "Distrik Kalimantan Timur",
        "name":  "Triton KB 8326 WA",
        "number":  "2000022847",
        "cost_center":  "5D02CAR005",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "28",
        "unit":  "Distrik Kalimantan Selatan",
        "name":  "Mobil Dinas Manager B 1875 TJT",
        "number":  "2000022662",
        "cost_center":  "5D03CAR001",
        "ket_cc":  "Mati",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Distrik Kalimantan Selatan",
        "name":  "Mobil Poll KB 1287 WZ",
        "number":  "2000022663",
        "cost_center":  "5D03CAR002",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Distrik Kalimantan Selatan",
        "name":  "Mobil Dinas PMO DA 8163 KJ",
        "number":  "2000022664",
        "cost_center":  "5D03CAR003",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Distrik Kalimantan Selatan",
        "name":  "Triton DA 8485 YC",
        "number":  "2000022713",
        "cost_center":  "5D03CAR004",
        "ket_cc":  "Mati 5F11SU0402",
        "ket_vhc":  "Tidak Ada BA",
        "status":  "",
        "kepemilikan":  "Sewa Raren"
    },
    {
        "no":  "",
        "unit":  "Distrik Kalimantan Selatan",
        "name":  "Mobil Group Manager KB 1841 DM",
        "number":  "2000022841",
        "cost_center":  "5D03CAR005",
        "ket_cc":  "BK 1179 AWA berubah KB 1841 DM",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    },
    {
        "no":  "",
        "unit":  "Distrik Kalimantan Selatan",
        "name":  "Mobil Pool KB 8923 WA",
        "number":  "2000022842",
        "cost_center":  "5D03CAR006",
        "ket_cc":  "",
        "ket_vhc":  "Aktif",
        "status":  "",
        "kepemilikan":  ""
    }
];
